[bot] # Configuration for the bot
prefix = "!"
owner = 168827261682843648 # DusterTheFirst
website = "https://whs-help.dusterthefirst.com"

[server] # Configuration for the server
id = 609141661884481543 # Server ID
admin_roles = [
    609146598756319292, # Moderator
    609146291389464577 # Admin
]
status_log = 635677461484404756

[roles] # Configuration about the roles
auto_assign = [] # Roles to auto assign on join (ex. "group" roles)
joined = 609171335016611841 # The role to show that a user has joined
tester = 629133561731088384 # The role that testers have (To save the bot effort during testing)